# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-18 12:11
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotfix',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='spotfix',
            name='longitude',
        ),
        migrations.AddField(
            model_name='spotfix',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default=None, srid=4326),
            preserve_default=False,
        ),
    ]
