# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-18 13:42
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20160618_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotfix',
            name='owner',
        ),
        migrations.AlterField(
            model_name='spotfix',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default=None, srid=4326),
        ),
    ]
