# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-18 13:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20160618_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotfix',
            name='gear',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
